name: CI - Run tests

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc poppler-utils

      - name: Run shell test scripts
        run: |
          chmod +x tests/*.sh
          ./tests/test_q3.sh
          ./tests/test_q6.sh
          ./tests/test_q8.sh
          ./tests/test_q9.sh
          ./tests/testq10.sh
          ./tests/test_pdf.sh
